package com.ticketsync.model;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents one row in the {@code audit_log} table.
 */
public class AuditLog {

    private int logId;
    private LocalDateTime timestamp;
    private String username;
    private String action;
    private String entityType;
    private Integer entityId;
    private String details;
    private String ipAddress;
    private String sessionId;

    /**
     * Default constructor for JDBC mapping.
     */
    public AuditLog() {
    }

    /**
     * Constructs an audit log with all mapped fields.
     *
     * @param logId       primary key generated by the database
     * @param timestamp   date and time when the event occurred; must not be null
     * @param username    username of the actor who triggered the event; must not be blank
     * @param action      action constant name (e.g. {@code "PURCHASE_SEATS"}); must not be blank
     * @param entityType  type of entity affected (e.g. {@code "SALE"}, {@code "USER"}); may be null
     * @param entityId    primary key of the affected entity; may be null
     * @param details     JSON string with additional context; may be null
     * @param ipAddress   IP address of the client; may be null
     * @param sessionId   session identifier; may be null
     */
    public AuditLog(int logId, LocalDateTime timestamp, String username, String action,
                    String entityType, Integer entityId, String details,
                    String ipAddress, String sessionId) {
        this.logId = logId;
        this.timestamp = timestamp;
        this.username = username;
        this.action = action;
        this.entityType = entityType;
        this.entityId = entityId;
        this.details = details;
        this.ipAddress = ipAddress;
        this.sessionId = sessionId;
    }

    /**
     * Returns the log identifier.
     *
     * @return database-generated primary key
     */
    public int getLogId() {
        return logId;
    }

    /**
     * Sets the log identifier.
     *
     * @param logId database-generated primary key
     */
    public void setLogId(int logId) {
        this.logId = logId;
    }

    /**
     * Returns the event timestamp.
     *
     * @return date and time when the audited event occurred
     */
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the event timestamp.
     *
     * @param timestamp date and time of the event; must not be null
     */
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Returns the username of the actor.
     *
     * @return username who triggered the event
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username of the actor.
     *
     * @param username actor's username; must not be null or blank
     */
    public void setUsername(String username) {
        if (username == null || username.isBlank()) {
            throw new IllegalArgumentException("username must not be null or blank");
        }
        this.username = username;
    }

    /**
     * Returns the action name.
     *
     * @return action constant name (e.g. {@code "PURCHASE_SEATS"})
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the action name.
     *
     * @param action action constant name; must not be null or blank
     */
    public void setAction(String action) {
        if (action == null || action.isBlank()) {
            throw new IllegalArgumentException("action must not be null or blank");
        }
        this.action = action;
    }

    /**
     * Returns the type of entity affected.
     *
     * @return entity type string (e.g. {@code "SALE"}, {@code "USER"}), or null
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the type of entity affected.
     *
     * @param entityType entity type string; may be null
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    /**
     * Returns the primary key of the affected entity.
     *
     * @return entity primary key, or null if not applicable
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * Sets the primary key of the affected entity.
     *
     * @param entityId entity primary key; may be null
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * Returns the details JSON string.
     *
     * @return JSON string with additional context for the event, or null
     */
    public String getDetails() {
        return details;
    }

    /**
     * Sets the details JSON string.
     *
     * @param details JSON string with additional context; may be null
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * Returns the IP address of the client.
     *
     * @return IP address string, or null if not recorded
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the IP address of the client.
     *
     * @param ipAddress client IP address; may be null
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * Returns the session identifier.
     *
     * @return session ID associated with the event, or null if not recorded
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the session identifier.
     *
     * @param sessionId session ID; may be null
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuditLog auditLog = (AuditLog) o;
        return logId == auditLog.logId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(logId);
    }

    @Override
    public String toString() {
        return "AuditLog{"
                + "logId=" + logId
                + ", timestamp=" + timestamp
                + ", username='" + username + '\''
                + ", action='" + action + '\''
                + ", entityType='" + entityType + '\''
                + ", entityId=" + entityId
                + '}';
    }
}
